[package]
name = "supsearch"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["demo/arc-1"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
num-bigint = "0.4"
num-complex = "0.4"
num-traits = "0.2"
rug = { version = "1.30", default-features = false, features = ["float"] }
gmp-mpfr-sys = { version = "1.7", default-features = false, features = ["mpfr", "c-no-tests"] }
