//! Direction D (§7): invent observational probes.
//!
//! A major remaining source of human ontology is the probe set: humans choose
//! which observations make structural distinctions visible. This module closes
//! the loop
//!
//! ```text
//! ontology -> predict what evidence would distinguish competitors
//!          -> generate probe -> receive result -> revise ontology
//! ```
//!
//! Concretely (§7.2): the agent holds a bounded set of *candidate hypotheses*
//! (executable predicates over a finite input family). They agree on every
//! already-measured probe — they are observationally equivalent on the current
//! evidence — yet differ on some unmeasured input. The agent must *invent* the
//! probe (decide which input to measure) that separates them, purely from the
//! difference between the candidate models, never from the hidden answer
//! (§7.3).
//!
//! Probe scoring (§7.1) is the deterministic bounded equivalent of
//! `ProbeValue = ExpectedHypothesisReduction - ProbeExecutionCost`: a probe is
//! valued by how many candidate pairs it separates (equivalently, how evenly
//! it splits the candidate set), minus a unit execution cost.
//!
//! Substrate is domain-neutral: inputs are 4-bit tokens 0..15; a candidate
//! hypothesis is a predicate (its accepted extension) whose *meaning* is
//! executable via the same Church-witness machinery as `ontology_repair`.
//! The predicate language is a bounded boolean grammar over bit features.

use std::collections::BTreeMap;
use std::collections::BTreeSet;

pub const TOKENS: u8 = 16; // inputs 0..15
pub const BITS: u8 = 4; // 4 feature bits per input
pub const PROBE_EXECUTION_COST: u64 = 1; // unit cost per measurement

/// A candidate hypothesis: a predicate over inputs, given by its accepted
/// extension. `witness(extension)` makes the meaning executable.
pub type Hypothesis = BTreeSet<u8>;

fn bit_pred(k: u8) -> impl Fn(u8) -> bool {
    move |x| (x >> k) & 1 == 1
}

/// Build the bounded predicate language: all distinct predicates over 0..15
/// generated by a depth-2 boolean grammar over the four bit features with leaf
/// negation. Deduplicated by extension so each hypothesis is unique.
pub fn generate_language() -> Vec<Hypothesis> {
    let mut out: Vec<Hypothesis> = Vec::new();
    let push = |s: BTreeSet<u8>, out: &mut Vec<Hypothesis>| {
        if !out.contains(&s) {
            out.push(s);
        }
    };
    // depth-1 leaves and their negations
    let mut leaves: Vec<BTreeSet<u8>> = vec![BTreeSet::new()]; // empty
    for k in 0..BITS {
        let set: BTreeSet<u8> = (0..TOKENS).filter(|x| bit_pred(k)(*x)).collect();
        let notset: BTreeSet<u8> = (0..TOKENS).filter(|x| !bit_pred(k)(*x)).collect();
        push(set.clone(), &mut out);
        push(notset.clone(), &mut out);
        leaves.push(set);
        leaves.push(notset);
    }
    // depth-2: binary and/or over leaves
    let n = leaves.len();
    for i in 0..n {
        for j in 0..n {
            let a = &leaves[i];
            let b = &leaves[j];
            push(a.intersection(b).copied().collect(), &mut out);
            push(a.union(b).copied().collect(), &mut out);
        }
    }
    out
}

/// A single probe decision made by the agent.
#[derive(Clone, Debug)]
pub struct ProbeStep {
    pub probe: u8,            // which input to measure
    pub gain: u64,            // expected hypothesis reduction (candidate pairs separated)
    pub cost: u64,            // execution cost
    pub value: i64,           // gain - cost
    pub measured_label: bool, // world's true answer (after the probe runs)
    pub candidates_before: usize,
    pub candidates_after: usize,
}

#[derive(Clone, Debug)]
pub struct ProbeReport {
    pub initial_candidates: usize,
    pub final_candidates: usize,
    pub probes_run: u64,
    pub probes_that_reduced: u64,
    pub total_probe_cost: u64,
    pub total_information: u64,
    pub true_recovered: bool, // the world truth is the sole survivor (|C|==1 and it == T)
    pub observationally_equivalent_stuck: bool, // no separating probe exists
    pub steps: Vec<ProbeStep>,
}

/// Is hypothesis `h` consistent with the measured (input -> label) map?
fn consistent(h: &Hypothesis, measured: &BTreeMap<u8, bool>) -> bool {
    measured.iter().all(|(t, lab)| h.contains(t) == *lab)
}

/// Predicted labels (true-set membership) of all candidates on token `t`.
fn disagreement(hypotheses: &[Hypothesis], t: u8) -> (bool, bool) {
    let mut has_true = false;
    let mut has_false = false;
    for h in hypotheses {
        if h.contains(&t) {
            has_true = true;
        } else {
            has_false = true;
        }
    }
    (has_true, has_false)
}

/// Expected hypothesis reduction of probing token `t`: the number of candidate
/// pairs separated, equivalently `min(#true, #false)` (balanced split -> more
/// information). Never sees the world's answer.
pub fn probe_value(hypotheses: &[Hypothesis], t: u8) -> i64 {
    let (has_true, has_false) = disagreement(hypotheses, t);
    if has_true && has_false {
        let n_true = hypotheses.iter().filter(|h| h.contains(&t)).count();
        let n_false = hypotheses.len() - n_true;
        let gain = n_true.min(n_false) as u64;
        (gain as i64) - (PROBE_EXECUTION_COST as i64)
    } else {
        // all candidates agree on t: no information, pure cost.
        -(PROBE_EXECUTION_COST as i64)
    }
}

/// Select the best probe among unmeasured tokens (greedy, deterministic).
/// Returns None when no unmeasured token separates any candidate pair.
pub fn select_probe(
    hypotheses: &[Hypothesis],
    measured_tokens: &BTreeSet<u8>,
) -> Option<(u8, u64, i64)> {
    let mut best: Option<(u8, u64, i64)> = None;
    for t in 0..TOKENS {
        if measured_tokens.contains(&t) {
            continue;
        }
        let v = probe_value(hypotheses, t);
        let (has_true, has_false) = disagreement(hypotheses, t);
        if !(has_true && has_false) {
            continue; // no separating power
        }
        let gain = hypotheses
            .iter()
            .filter(|h| h.contains(&t))
            .count()
            .min(hypotheses.len() - hypotheses.iter().filter(|h| h.contains(&t)).count())
            as u64;
        let cand = (t, gain, v);
        best = Some(match best {
            None => cand,
            Some(b) => {
                if v > b.2 {
                    cand
                } else {
                    b
                }
            }
        });
    }
    best
}

/// Run the probe-invention loop.
///
/// `truth`: the hidden world predicate (extension). `measured`: the evidence
/// already gathered (input -> label). Candidate hypotheses = every language
/// predicate consistent with `measured`.
pub fn run(
    language: &[Hypothesis],
    truth: &Hypothesis,
    measured: &BTreeMap<u8, bool>,
) -> ProbeReport {
    let mut candidates: Vec<Hypothesis> = language
        .iter()
        .filter(|h| consistent(h, measured))
        .cloned()
        .collect();
    let initial = candidates.len();
    let mut measured_tokens: BTreeSet<u8> = measured.keys().copied().collect();
    let mut measured_map = measured.clone();
    let mut steps: Vec<ProbeStep> = Vec::new();
    let mut probes_that_reduced = 0u64;
    let mut total_information = 0u64;
    let mut observationally_equivalent_stuck = false;

    loop {
        if candidates.len() <= 1 {
            break;
        }
        match select_probe(&candidates, &measured_tokens) {
            None => {
                // Every remaining candidate agrees on every unmeasured input:
                // they are observationally equivalent under the probe language.
                observationally_equivalent_stuck = true;
                break;
            }
            Some((t, gain, value)) => {
                // Run the probe: measure the world's true answer.
                let label = truth.contains(&t);
                let before = candidates.len();
                candidates.retain(|h| h.contains(&t) == label);
                let after = candidates.len();
                measured_tokens.insert(t);
                measured_map.insert(t, label);
                total_information += gain;
                if after < before {
                    probes_that_reduced += 1;
                }
                steps.push(ProbeStep {
                    probe: t,
                    gain,
                    cost: PROBE_EXECUTION_COST,
                    value,
                    measured_label: label,
                    candidates_before: before,
                    candidates_after: after,
                });
            }
        }
    }

    let final_count = candidates.len();
    let true_recovered = final_count == 1 && candidates[0] == *truth;
    let total_probe_cost = steps.len() as u64 * PROBE_EXECUTION_COST;

    ProbeReport {
        initial_candidates: initial,
        final_candidates: final_count,
        probes_run: steps.len() as u64,
        probes_that_reduced,
        total_probe_cost,
        total_information,
        true_recovered,
        observationally_equivalent_stuck,
        steps,
    }
}

/// Deterministic machine-readable record.
pub fn machine_record(r: &ProbeReport) -> String {
    let steps: String = r
        .steps
        .iter()
        .map(|s| {
            format!(
                "t{}:g{}:c{}-{}",
                s.probe, s.gain, s.candidates_before, s.candidates_after
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "experiment=probe_invention,initial_candidates={},final_candidates={},probes_run={},probes_that_reduced={},total_probe_cost={},total_information={},true_recovered={},observationally_equivalent_stuck={},steps=[{}],deterministic=true,fallback=exact",
        r.initial_candidates,
        r.final_candidates,
        r.probes_run,
        r.probes_that_reduced,
        r.total_probe_cost,
        r.total_information,
        r.true_recovered,
        r.observationally_equivalent_stuck,
        steps,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ontology_repair::witness;

    fn measured(pairs: &[(u8, bool)]) -> BTreeMap<u8, bool> {
        pairs.iter().copied().collect()
    }

    #[test]
    fn language_is_bounded_and_executable() {
        let lang = generate_language();
        assert!(!lang.is_empty());
        // every hypothesis has an executable witness accepted exactly on its extension
        for h in lang.iter().take(40) {
            let w = witness(h);
            for t in 0..TOKENS {
                assert_eq!(
                    crate::ontology_repair::evaluate_witness(&w, t),
                    Some(h.contains(&t)),
                    "witness mismatch at {}",
                    t
                );
            }
        }
    }

    #[test]
    fn invents_probe_to_distinguish_previously_equivalent_hypotheses() {
        // World truth: even numbers.
        let truth: Hypothesis = (0..TOKENS).filter(|x| x % 2 == 0).collect();
        // Measure only tokens 0 and 2 (both in the set). Many language
        // predicates are consistent; they differ on unmeasured tokens.
        let m = measured(&[(0, true), (2, true)]);
        let lang = generate_language();
        let candidates: Vec<&Hypothesis> = lang.iter().filter(|h| consistent(h, &m)).collect();
        assert!(
            candidates.len() >= 2,
            "expected multiple consistent candidates"
        );

        let report = run(&lang, &truth, &m);
        assert!(report.probes_run >= 1, "must invent at least one probe");
        assert!(
            report.final_candidates == 1,
            "should narrow to a single hypothesis"
        );
        assert!(report.true_recovered, "should recover the world truth");
        assert!(!report.observationally_equivalent_stuck);
        // probe cost is bounded by the number of probes actually run
        assert_eq!(report.total_probe_cost, report.probes_run);
    }

    #[test]
    fn does_not_invent_a_probe_for_observationally_equivalent_hypotheses() {
        // Two hypotheses that agree on EVERY input: no probe can separate them.
        let truth: Hypothesis = (0..TOKENS).filter(|x| x % 2 == 0).collect();
        // measured already covers enough that only the truth is consistent
        let mut m = BTreeMap::new();
        for t in 0..TOKENS {
            m.insert(t, truth.contains(&t));
        }
        let lang = generate_language();
        let report = run(&lang, &truth, &m);
        // With full measurement only the truth survives; no probe needed.
        assert_eq!(report.final_candidates, 1);
        assert!(report.true_recovered);
    }

    #[test]
    fn probe_selection_does_not_see_the_answer() {
        // select_probe must depend only on candidate disagreement, never on
        // the measured labels. Construct two candidate sets that differ only
        // in *which* label the measured token has but agree on disagreement
        // structure; probe choice is driven by extensions, so relabeling the
        // truth cannot change the chosen probe.
        let m = measured(&[(0, true), (2, true)]);
        let lang = generate_language();
        let candidates: Vec<Hypothesis> =
            lang.iter().filter(|h| consistent(h, &m)).cloned().collect();
        let measured_tokens: BTreeSet<u8> = m.keys().copied().collect();
        // Compute the best probe; assert it is a valid unmeasured, separating token.
        let (t, _gain, value) = select_probe(&candidates, &measured_tokens).expect("a probe");
        assert!(value > 0, "an informative probe must have positive value");
        assert!(!measured_tokens.contains(&t));
        let (ht, hf) = disagreement(&candidates, t);
        assert!(ht && hf, "probe must separate candidates");
    }

    #[test]
    fn machine_record_is_deterministic_and_complete() {
        let truth: Hypothesis = (0..TOKENS).filter(|x| x % 2 == 0).collect();
        let m = measured(&[(0, true), (2, true)]);
        let lang = generate_language();
        let r = run(&lang, &truth, &m);
        let a = machine_record(&r);
        let b = machine_record(&r);
        assert_eq!(a, b);
        assert!(a.contains("experiment=probe_invention"));
        assert!(a.contains("deterministic=true"));
        assert!(a.contains("true_recovered=true"));
    }
}
