//! Fair synthesis of recursive laws in the universal lambda language.
//!
//! This is the unbounded counterpart to finite recurrence pattern matching.
//! Candidate functionals `F` are generated by syntax size, converted to
//! executable fixed points, and tested with increasing evaluation fuel. No
//! fold-shaped grammar, recursion primitive, data representation, arity, or
//! descent relation is assumed.
//!
//! Completeness is necessarily relative: if a closed finite functional exists
//! in [`crate::universal`]'s language and all observations of its fixed point
//! terminate within finite fuel, then the diagonal schedule reaches a stage at
//! which it is tested. Program equivalence and rejection of every false law are
//! undecidable; discovery and extrapolation suites remain finite falsifiers.

use crate::{
    fixpoint, nbe,
    term::{self, Term},
    universal,
};
use std::collections::HashSet;
use std::rc::Rc;

#[derive(Clone, Debug)]
pub struct Example {
    pub arguments: Vec<Rc<Term>>,
    pub expected: Rc<Term>,
}

#[derive(Clone, Debug)]
pub struct SearchProblem {
    /// Finite closed ontology alphabet. Empty means pure lambda calculus.
    pub atoms: Vec<Rc<Term>>,
    /// Programs/behaviors used to propose a law.
    pub discovery: Vec<Example>,
    /// Independently selected unseen cases required before admission.
    pub extrapolation: Vec<Example>,
    /// Reject a functional that never refers to its recursive parameter.
    pub require_recursive_reference: bool,
    /// Reject dead recursive references by replacing the recursive value with
    /// a neutral sentinel and requiring at least one observed behavior to change.
    pub require_load_bearing_recursion: bool,
    /// Adversarial control against constant-output recurrences. Enable when the
    /// target family is expected to exhibit more than one behavior.
    pub require_distinct_outputs: bool,
}

#[derive(Clone, Debug)]
pub struct RecursiveCandidate {
    pub functional: Rc<Term>,
    pub executable: Rc<Term>,
    pub syntax_size: u32,
    pub fuel: u64,
}

/// Test one proposed functional with three independent gates:
///
/// 1. it reproduces discovery behaviors;
/// 2. its fixed-point equation holds on discovery arguments;
/// 3. it reproduces unseen extrapolation behaviors.
pub fn validate_functional(
    functional: &Rc<Term>,
    problem: &SearchProblem,
    fuel: i64,
) -> Option<Rc<Term>> {
    if problem.discovery.is_empty()
        || problem.extrapolation.is_empty()
        || (problem.require_recursive_reference && !uses_recursive_parameter(functional))
        || (problem.require_distinct_outputs && !targets_vary(problem, fuel))
        || problem
            .atoms
            .iter()
            .chain(
                problem
                    .discovery
                    .iter()
                    .chain(&problem.extrapolation)
                    .flat_map(|e| e.arguments.iter().chain(std::iter::once(&e.expected))),
            )
            .any(|t| !crate::transform::is_closed(t))
    {
        return None;
    }
    let executable = fixpoint::synthesize(functional)?;
    if !examples_hold(&executable, &problem.discovery, fuel)
        || !fixpoint::equation_holds(
            functional,
            &problem
                .discovery
                .iter()
                .map(|e| e.arguments.clone())
                .collect::<Vec<_>>(),
            fuel,
        )
        || !examples_hold(&executable, &problem.extrapolation, fuel)
        || (problem.require_load_bearing_recursion
            && !recursion_is_load_bearing(functional, &executable, problem, fuel))
    {
        return None;
    }
    Some(executable)
}

fn targets_vary(problem: &SearchProblem, fuel: i64) -> bool {
    let mut targets = problem.discovery.iter().chain(&problem.extrapolation);
    let Some(first) = targets.next().and_then(|e| normalize(&e.expected, fuel)) else {
        return false;
    };
    targets.any(|example| normalize(&example.expected, fuel).is_some_and(|target| target != first))
}

/// Exhaustively test the finite class at one diagonal resource point.
pub fn search_stage(
    problem: &SearchProblem,
    syntax_size: u32,
    fuel: u64,
) -> Vec<RecursiveCandidate> {
    let Ok(fuel_i64) = i64::try_from(fuel) else {
        return Vec::new();
    };
    universal::terms_exact(syntax_size, 0, &problem.atoms)
        .into_iter()
        .filter_map(|functional| {
            let executable = validate_functional(&functional, problem, fuel_i64)?;
            Some(RecursiveCandidate {
                functional,
                executable,
                syntax_size,
                fuel,
            })
        })
        .collect()
}

/// A cap-free semidecision stream. `next()` may run forever when no solution
/// exists, as any sound claim of total failure would contradict universality.
pub struct FairRecursiveSearch<'a> {
    problem: &'a SearchProblem,
    schedule: universal::Dovetail,
    pending: std::vec::IntoIter<RecursiveCandidate>,
    yielded: HashSet<Rc<Term>>,
}

impl<'a> FairRecursiveSearch<'a> {
    pub fn new(problem: &'a SearchProblem) -> Self {
        Self {
            problem,
            schedule: universal::Dovetail::default(),
            pending: Vec::new().into_iter(),
            yielded: HashSet::new(),
        }
    }
}

impl Iterator for FairRecursiveSearch<'_> {
    type Item = RecursiveCandidate;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            if let Some(candidate) = self.pending.next() {
                if self.yielded.insert(candidate.functional.clone()) {
                    return Some(candidate);
                }
            } else {
                let (size, fuel) = self.schedule.next()?;
                self.pending = search_stage(self.problem, size, fuel).into_iter();
            }
        }
    }
}

fn examples_hold(program: &Rc<Term>, examples: &[Example], fuel: i64) -> bool {
    examples.iter().all(|example| {
        let observed = example
            .arguments
            .iter()
            .fold(program.clone(), |f, x| term::app(f, x.clone()));
        normalize(&observed, fuel)
            .zip(normalize(&example.expected, fuel))
            .is_some_and(|(a, b)| a == b)
    })
}

fn recursion_is_load_bearing(
    functional: &Rc<Term>,
    executable: &Rc<Term>,
    problem: &SearchProblem,
    fuel: i64,
) -> bool {
    // A neutral sentinel survives normalization exactly when recursive data
    // flow is observable. Unlike Ω, it also makes ablation safe at large fuel.
    let sentinel = Rc::new(Term::Free(u32::MAX - 100));
    let ablated = term::app(functional.clone(), sentinel);
    problem
        .discovery
        .iter()
        .chain(&problem.extrapolation)
        .any(|example| {
            let recursive = example
                .arguments
                .iter()
                .fold(executable.clone(), |f, x| term::app(f, x.clone()));
            let nonrecursive = example
                .arguments
                .iter()
                .fold(ablated.clone(), |f, x| term::app(f, x.clone()));
            match (normalize(&recursive, fuel), normalize(&nonrecursive, fuel)) {
                (Some(a), Some(b)) => a != b,
                (Some(_), None) => true,
                _ => false,
            }
        })
}

/// Does the body of `λrecursive. ...` refer to that binder at any depth?
pub fn uses_recursive_parameter(functional: &Rc<Term>) -> bool {
    let Term::Lam(body) = functional.as_ref() else {
        return false;
    };
    refers_to_outer(body, 0)
}

fn refers_to_outer(t: &Rc<Term>, nested_lambdas: u32) -> bool {
    match t.as_ref() {
        Term::Var(index) => *index == nested_lambdas,
        Term::Lam(body) => refers_to_outer(body, nested_lambdas + 1),
        Term::App(f, a) => refers_to_outer(f, nested_lambdas) || refers_to_outer(a, nested_lambdas),
        Term::Prim(_) | Term::Free(_) => false,
    }
}

fn normalize(t: &Rc<Term>, fuel: i64) -> Option<Rc<Term>> {
    nbe::normalize(&Rc::new(Vec::new()), t, &mut nbe::Fuel(fuel)).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{acquire, bank, parse};

    fn scott_zero() -> Rc<Term> {
        term::lam(term::lam(term::var(1)))
    }

    fn scott_succ() -> Rc<Term> {
        term::lam(term::lam(term::lam(term::app(term::var(0), term::var(2)))))
    }

    fn scott(n: u32) -> Rc<Term> {
        (0..n).fold(scott_zero(), |x, _| term::app(scott_succ(), x))
    }

    fn copy_functional() -> Rc<Term> {
        let step = term::lam(term::app(
            scott_succ(),
            term::app(term::var(2), term::var(0)),
        ));
        term::lam(term::lam(term::app(
            term::app(term::var(0), scott_zero()),
            step,
        )))
    }

    fn problem() -> SearchProblem {
        SearchProblem {
            atoms: vec![],
            discovery: (0..=3)
                .map(|n| Example {
                    arguments: vec![scott(n)],
                    expected: scott(n),
                })
                .collect(),
            extrapolation: [5, 7, 9]
                .into_iter()
                .map(|n| Example {
                    arguments: vec![scott(n)],
                    expected: scott(n),
                })
                .collect(),
            require_recursive_reference: true,
            require_load_bearing_recursion: true,
            require_distinct_outputs: true,
        }
    }

    #[test]
    fn validates_recursive_law_discovery_equation_and_extrapolation() {
        let functional = copy_functional();
        assert!(validate_functional(&functional, &problem(), 10_000).is_some());
    }

    #[test]
    fn rejects_nonrecursive_observational_shortcut() {
        let identity_functional = term::lam(term::lam(term::var(0)));
        assert!(!uses_recursive_parameter(&identity_functional));
        assert!(validate_functional(&identity_functional, &problem(), 10_000).is_none());
    }

    #[test]
    fn rejects_a_dead_recursive_reference() {
        // λr.λx.(λignored.x) r
        let dead = term::lam(term::lam(term::app(term::lam(term::var(1)), term::var(1))));
        assert!(uses_recursive_parameter(&dead));
        assert!(validate_functional(&dead, &problem(), 10_000).is_none());
    }

    #[test]
    fn rejects_constant_output_training_families_when_controlled() {
        // λr.λn. n zero r recursively descends, but every result is zero.
        let constant_recursive = term::lam(term::lam(term::app(
            term::app(term::var(0), scott_zero()),
            term::var(1),
        )));
        let constant_example = |n| Example {
            arguments: vec![scott(n)],
            expected: scott_zero(),
        };
        let constant_problem = SearchProblem {
            atoms: vec![],
            discovery: (0..=3).map(constant_example).collect(),
            extrapolation: [5, 7, 9].into_iter().map(constant_example).collect(),
            require_recursive_reference: true,
            require_load_bearing_recursion: true,
            require_distinct_outputs: true,
        };
        assert!(validate_functional(&constant_recursive, &constant_problem, 10_000).is_none());
    }

    #[test]
    fn target_has_a_finite_fair_search_stage() {
        let target = copy_functional();
        assert!(universal::in_language(&target, 0, &[]));
        let stage = universal::scheduled_stage(target.size(), 10_000).unwrap();
        assert!(stage < u64::MAX);
        // At this finite point the target is admitted; exhaustive enumeration
        // of its exact finite size class therefore contains a solution.
        assert!(validate_functional(&target, &problem(), 10_000).is_some());
    }

    fn church_bool(value: bool) -> Rc<Term> {
        if value {
            term::lam(term::lam(term::var(1)))
        } else {
            term::lam(term::lam(term::var(0)))
        }
    }

    fn chain(depth: u32) -> Rc<Term> {
        let not = term::lam(term::app(
            term::app(term::var(0), church_bool(false)),
            church_bool(true),
        ));
        (0..depth).fold(term::lam(church_bool(false)), |tail, _| {
            term::lam(term::app(not.clone(), term::app(term::var(0), tail)))
        })
    }

    #[test]
    fn finite_fair_stage_actually_discovers_a_recursive_functional() {
        // Anonymous data values receive their recursive interpreter as an
        // argument. The unknown law is simply λr.λvalue.value r.
        let target = term::lam(term::lam(term::app(term::var(0), term::var(1))));
        let make_example = |depth| Example {
            arguments: vec![chain(depth)],
            expected: church_bool(depth % 2 == 1),
        };
        let problem = SearchProblem {
            atoms: vec![],
            discovery: (0..=3).map(make_example).collect(),
            extrapolation: [5, 7, 9].into_iter().map(make_example).collect(),
            require_recursive_reference: true,
            require_load_bearing_recursion: true,
            require_distinct_outputs: true,
        };
        let candidates = search_stage(&problem, target.size(), 10_000);
        assert!(candidates
            .iter()
            .any(|candidate| candidate.functional == target));
    }

    fn ackermann_functional() -> Rc<Term> {
        let one = term::app(scott_succ(), scott_zero());
        let nested = term::lam(term::app(
            term::app(term::var(4), term::var(1)),
            term::app(
                term::app(term::var(4), term::app(scott_succ(), term::var(1))),
                term::var(0),
            ),
        ));
        let m_step = term::lam(term::app(
            term::app(
                term::var(1),
                term::app(term::app(term::var(3), term::var(0)), one),
            ),
            nested,
        ));
        term::lam(term::lam(term::lam(term::app(
            term::app(term::var(1), term::app(scott_succ(), term::var(0))),
            m_step,
        ))))
    }

    #[test]
    fn invented_nonstructural_law_earns_counterfactual_primitive_status() {
        let executable = fixpoint::synthesize(&ackermann_functional()).unwrap();
        let cases = [(0, 2, 3), (1, 2, 4), (2, 1, 5), (2, 2, 7)];
        let task = parse::Task {
            arity: 2,
            tests: cases
                .into_iter()
                .map(|(m, n, expected)| parse::Test {
                    args: vec![scott(m), scott(n)],
                    want: scott(expected),
                    outer: 0,
                })
                .collect(),
        };
        let opts = bank::Options {
            max_size: 5,
            max_depth: 2,
            fuel: 20_000_000,
            time_budget_secs: 2.0,
            max_level_entries: 100_000,
            max_opaque_entries: 10_000,
            seeds: vec![],
            concepts: vec![],
        };
        let before = acquire::concept_cost(&task, &[], &opts);
        let concept = bank::Concept {
            body: executable,
            name: "invented-ackermann".into(),
            arity: 2,
        };
        let after = acquire::concept_cost(&task, &[concept], &opts);
        let gain = acquire::Gain {
            arity: 2,
            before,
            after,
        };
        assert!(
            gain.frontier(),
            "expected frontier gain, got {before} → {after}"
        );
    }
}
